### ISSUE TITLE
AttributeError: 'list' object has no attribute 'fit_table'

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis-ml#137]
When I run this code:

```py
import ibis
import ibis_ml as ml

con = ibis.connect("duckdb://nycflights13.ddb")
con.create_table(
    "flights", ibis.examples.nycflights13_flights.fetch().to_pyarrow(), overwrite=True
)
flights = con.table("flights")

recipe = ml.Recipe(
    [
        ml.ScaleStandard("distance")
    ]
)
recipe.fit(flights)
```

I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/ibis_ml/core.py", line 562, in fit
    self._fit_table(table, targets, index)
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/ibis_ml/core.py", line 511, in _fit_table
    step.fit_table(table, metadata)
    ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'fit_table'
```

**Comment by jcrist** [comment]
The recipe constructor is variadic (it takes one or more steps as args, not a list of steps). You want:

```python
recipe = ml.Recipe(
    ml.ScaleStandard("distance")
)
```

**Comment by ianmcook** [comment]
Aha, thanks! I got tripped up on this because in a very early version of IbisML, it took a list of steps.
